# Generated by Django 4.0.2 on 2022-02-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=755, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('', 'Select the tag'), ('Trading', 'Trading'), ('Conference', 'Conference'), ('Networking', 'Networking')], max_length=100, null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attendee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(blank=True, choices=[('', 'Select the location'), ('Bengaluru', 'Bengaluru'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], max_length=100, null=True)),
                ('capacity', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(blank=True, default=10, null=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_details', to='event_app.event')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_details', to='event_app.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no', models.IntegerField(blank=True, default=1, null=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_details', to='event_app.show')),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_user', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_details', to='event_app.seat')),
            ],
        ),
    ]
